---
title: "James Szewczyk"
---

PhD Student

Department of Political Science, Emory University 

Curriculum Vitae 

### Contact Information: 

Email: james.szewczyk@emory.edu

U.S. Mail:
Department of Political Science,
Emory University,
1555 Dickey Drive,
Atlanta, Georgia 30322



### Research Interests:

American political institutions, elections, public policy, representation  

### Working Papers: 

"How Electoral Institutions Affect Political Accountability: Evidence from Vote-by-Mail in Washington."

In this paper, I develop a theory of how vote-by-mail increases the probability that voters obtain political information before voting, which induces incumbents behave competently and more in line with the interests of their constituents. Exploiting the staggered implementation of vote-by-mail in Washington and a number of sources of data, I utilize a difference-in-differences estimation strategy to test this theory on the behavior of voters and elected officials in the state. I find that vote-by-mail causes a decrease in ballot roll-off on statewide ballot measures in presidential election years, which is consistent with the theory that voters gather more information when voting in all-mail elections. Further, switching from traditional polling place elections to vote-by-mail results in a decrease in negative findings on accountability audit reports and a decrease in taxing and spending in Washington's municipalities. Using data from the Catalist voter file I show that these results cannot be explained by changes in the composition of the electorate.

"The Effects of Community Income Inequality on Political Participation" (with Melody Crowder-Meyer)

TEST

"Voting Restrictions and Representation in Congress."
